{% set name = "napari-yolov5" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-yolov5-{{ version }}.tar.gz
  sha256: a01b55ac1573a678e2a68e5679f431313ade4cb5cfc8969abcbb78513fda930c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - connected-components-3d >=3.6.0
    - flask
    - imageio-ffmpeg  # pip check
    - magicgui <0.4.0
    - matplotlib-base >=3.2.2
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy >=1.18.5
    - opencv >=4.1.2
    - pillow >=7.1.2
    - python >={{ python_min }}
    - pyyaml >=5.3.1
    - qtpy
    - requests >=2.23.0
    - scipy >=1.4.1
    - seaborn >=0.11.2
    - tensorboard >=1.15.0
    - tensorflow
    - pytorch >=1.9.0
    - scikit-image
    - torchvision >=0.8.1
    - tqdm >=4.41.0
    - wandb

test:
  imports:
    - napari_yolov5
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rdemets/napari-yolov5
  summary: Plugin adapted from Ultralytics to bring YOLOv5 into Napari
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - rdemets
